const ComponentList = [
  { name: 'Alert',                type: 'modal'        },
  { name: 'Animated Menu Button', type: 'action'       },
  { name: 'App Wrapper',          type: 'layout'       },
  { name: 'Button Toggle',        type: 'action'       },
  { name: 'Button',               type: 'action'       },
  { name: 'Carousel',             type: 'layout'       },
  { name: 'Checkbox',             type: 'form'         },
  { name: 'Confirm',              type: 'modal'        },
  { name: 'Content',              type: 'layout'       },
  { name: 'Create',               type: 'action'       },
  { name: 'Date',                 type: 'form'         },
  { name: 'Decimal',              type: 'form'         },
  { name: 'Detail',               type: 'layout'       },
  { name: 'Dialog Full Screen',   type: 'modal'        },
  { name: 'Dialog',               type: 'modal'        },
  { name: 'Dropdown Filter Ajax', type: 'form'         },
  { name: 'Dropdown Filter',      type: 'form'         },
  { name: 'Dropdown',             type: 'form'         },
  { name: 'Fieldset',             type: 'form'         },
  { name: 'Filter',               type: 'form'         },
  { name: 'Flash',                type: 'notification' },
  { name: 'Form',                 type: 'form'         },
  { name: 'Heading',              type: 'layout'       },
  { name: 'Help',                 type: 'misc'         },
  { name: 'I18n',                 type: 'misc'         },
  { name: 'Icon',                 type: 'misc'         },
  { name: 'Link',                 type: 'action'       },
  { name: 'Menu',                 type: 'action'       },
  { name: 'Message',              type: 'notification' },
  { name: 'Multi Action Button',  type: 'action'       },
  { name: 'Multi Step Wizard',    type: 'action'       },
  { name: 'Navigation Bar',       type: 'layout'       },
  { name: 'Number',               type: 'form'         },
  { name: 'Pill',                 type: 'misc'         },
  { name: 'Pod',                  type: 'layout'       },
  { name: 'Portrait',             type: 'misc'         },
  { name: 'Profile',              type: 'misc'         },
  { name: 'Radio Button',         type: 'form'         },
  { name: 'Rainbow',              type: 'chart'        },
  { name: 'Row',                  type: 'layout'       },
  { name: 'Show Edit Pod',        type: 'layout'       },
  { name: 'Sidebar',              type: 'modal'        },
  { name: 'Spinner',              type: 'misc'         },
  { name: 'Split Button',         type: 'action'       },
  { name: 'Table Ajax',           type: 'grid'         },
  { name: 'Table',                type: 'grid'         },
  { name: 'Tabs',                 type: 'layout'       },
  { name: 'Textarea',             type: 'form'         },
  { name: 'Textbox',              type: 'form'         },
  { name: 'Toast',                type: 'notification' },
  { name: 'Tooltip',              type: 'misc'         },
  { name: 'Validations',          type: 'form'         }
];

export default ComponentList;
