const ComponentList = [
  { name: 'Alert',                href: 'alert',                type: 'modal'        },
  { name: 'Animated Menu Button', href: 'animated-menu-button', type: 'action'       },
  { name: 'App Wrapper',          href: 'app-wrapper',          type: 'layout'       },
  { name: 'Button Toggle',        href: 'button-toggle',        type: 'action'       },
  { name: 'Button',               href: 'button',               type: 'action'       },
  { name: 'Carousel',             href: 'carousel',             type: 'layout'       },
  { name: 'Checkbox',             href: 'checkbox',             type: 'form'         },
  { name: 'Confirm',              href: 'confirm',              type: 'modal'        },
  { name: 'Content',              href: 'content',              type: 'layout'       },
  { name: 'Create',               href: 'create',               type: 'action'       },
  { name: 'Date',                 href: 'date',                 type: 'form'         },
  { name: 'Decimal',              href: 'decimal',              type: 'form'         },
  { name: 'Detail',               href: 'detail',               type: 'layout'       },
  { name: 'Dialog Full Screen',   href: 'dialog-full-screen',   type: 'modal'        },
  { name: 'Dialog',               href: 'dialog',               type: 'modal'        },
  { name: 'Dropdown Filter Ajax', href: 'dropdown-filter-ajax', type: 'form'         },
  { name: 'Dropdown Filter',      href: 'dropdown-filter',      type: 'form'         },
  { name: 'Dropdown',             href: 'dropdown',             type: 'form'         },
  { name: 'Fieldset',             href: 'fieldset',             type: 'form'         },
  { name: 'Filter',               href: 'filter',               type: 'form'         },
  { name: 'Flash',                href: 'flash',                type: 'notification' },
  { name: 'Form',                 href: 'form',                 type: 'form'         },
  { name: 'Heading',              href: 'heading',              type: 'layout'       },
  { name: 'Help',                 href: 'help',                 type: 'misc'         },
  { name: 'I18n',                 href: 'i18n',                 type: 'misc'         },
  { name: 'Icon',                 href: 'icon',                 type: 'misc'         },
  { name: 'Link',                 href: 'link',                 type: 'action'       },
  { name: 'Menu',                 href: 'menu',                 type: 'action'       },
  { name: 'Message',              href: 'message',              type: 'notification' },
  { name: 'Multi Action Button',  href: 'multi-action-button',  type: 'action'       },
  { name: 'Multi Step Wizard',    href: 'multi-step-wizard',    type: 'action'       },
  { name: 'Navigation Bar',       href: 'navigation-bar',       type: 'layout'       },
  { name: 'Number',               href: 'number',               type: 'form'         },
  { name: 'Pill',                 href: 'pill',                 type: 'misc'         },
  { name: 'Pod',                  href: 'pod',                  type: 'layout'       },
  { name: 'Portrait',             href: 'portrait',             type: 'misc'         },
  { name: 'Profile',              href: 'profile',              type: 'misc'         },
  { name: 'Radio Button',         href: 'radio-button',         type: 'form'         },
  { name: 'Rainbow',              href: 'rainbow',              type: 'chart'        },
  { name: 'Row',                  href: 'row',                  type: 'layout'       },
  { name: 'Show Edit Pod',        href: 'show-edit-pod',        type: 'layout'       },
  { name: 'Sidebar',              href: 'sidebar',              type: 'modal'        },
  { name: 'Spinner',              href: 'spinner',              type: 'misc'         },
  { name: 'Split Button',         href: 'split-button',         type: 'action'       },
  { name: 'Table Ajax',           href: 'table-ajax',           type: 'grid'         },
  { name: 'Table',                href: 'table',                type: 'grid'         },
  { name: 'Tabs',                 href: 'tabs',                 type: 'layout'       },
  { name: 'Textarea',             href: 'textarea',             type: 'form'         },
  { name: 'Textbox',              href: 'textbox',              type: 'form'         },
  { name: 'Toast',                href: 'toast',                type: 'notification' },
  { name: 'Tooltip',              href: 'tooltip',              type: 'misc'         },
  { name: 'Validations',          href: 'validations',          type: 'form'         }
];

export default ComponentList;
