const ComponentList = [
  { name: 'Alert',                type: 'modal',        tags: [] },
  { name: 'Animated Menu Button', type: 'action',       tags: ['quick', 'start', 'circle'] },
  { name: 'App Wrapper',          type: 'layout',       tags: [] },
  { name: 'Button Toggle',        type: 'action',       tags: [] },
  { name: 'Button',               type: 'action',       tags: [] },
  { name: 'Carousel',             type: 'layout',       tags: [] },
  { name: 'Checkbox',             type: 'form',         tags: ['input'] },
  { name: 'Confirm',              type: 'modal',        tags: [] },
  { name: 'Content',              type: 'layout',       tags: [] },
  { name: 'Create',               type: 'action',       tags: [] },
  { name: 'Date',                 type: 'form',         tags: ['input'] },
  { name: 'Decimal',              type: 'form',         tags: ['input'] },
  { name: 'Detail',               type: 'layout',       tags: [] },
  { name: 'Dialog Full Screen',   type: 'modal',        tags: [] },
  { name: 'Dialog',               type: 'modal',        tags: [] },
  { name: 'Dropdown Filter Ajax', type: 'form',         tags: ['input'] },
  { name: 'Dropdown Filter',      type: 'form',         tags: ['input'] },
  { name: 'Dropdown',             type: 'form',         tags: ['input'] },
  { name: 'Fieldset',             type: 'form',         tags: [] },
  { name: 'Filter',               type: 'form',         tags: [] },
  { name: 'Flash',                type: 'notification', tags: [] },
  { name: 'Form',                 type: 'form',         tags: [] },
  { name: 'Heading',              type: 'layout',       tags: [] },
  { name: 'Help',                 type: 'misc',         tags: [] },
  { name: 'I18n',                 type: 'misc',         tags: ['translation'] },
  { name: 'Icon',                 type: 'misc',         tags: [] },
  { name: 'Link',                 type: 'action',       tags: ['anchor'] },
  { name: 'Menu',                 type: 'action',       tags: [] },
  { name: 'Message',              type: 'notification', tags: [] },
  { name: 'Multi Action Button',  type: 'action',       tags: [] },
  { name: 'Multi Step Wizard',    type: 'action',       tags: [] },
  { name: 'Navigation Bar',       type: 'layout',       tags: [] },
  { name: 'Number',               type: 'form',         tags: ['input'] },
  { name: 'Pill',                 type: 'misc',         tags: [] },
  { name: 'Pod',                  type: 'layout',       tags: [] },
  { name: 'Portrait',             type: 'misc',         tags: [] },
  { name: 'Profile',              type: 'misc',         tags: [] },
  { name: 'Radio Button',         type: 'form',         tags: ['input'] },
  { name: 'Rainbow',              type: 'chart',        tags: [] },
  { name: 'Row',                  type: 'layout',       tags: [] },
  { name: 'Show Edit Pod',        type: 'layout',       tags: [] },
  { name: 'Sidebar',              type: 'modal',        tags: [] },
  { name: 'Spinner',              type: 'misc',         tags: [] },
  { name: 'Split Button',         type: 'action',       tags: [] },
  { name: 'Table Ajax',           type: 'grid',         tags: ['grid'] },
  { name: 'Table',                type: 'grid',         tags: ['grid'] },
  { name: 'Tabs',                 type: 'layout',       tags: [] },
  { name: 'Textarea',             type: 'form',         tags: ['input'] },
  { name: 'Textbox',              type: 'form',         tags: ['input'] },
  { name: 'Toast',                type: 'notification', tags: [] },
  { name: 'Tooltip',              type: 'misc',         tags: [] },
  { name: 'Validations',          type: 'form',         tags: [] }
];

export default ComponentList;
