FROM cypress/included:3.8.1

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . $APP_HOME
RUN rm package-lock.json

# install packages
RUN apt-get update && \
    apt-get install -y curl \
    wget \
    openjdk-8-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

EXPOSE 9001

# Override default entrypoint from cypress/included
ENTRYPOINT []

RUN npm install -g wait-on --silent
RUN npm install --silent