FROM cypress/included:3.7.0

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . ./
RUN rm package-lock.json

EXPOSE 9001

# Override default entrypoint from cypress/included
ENTRYPOINT []

RUN npm install -g wait-on --silent
RUN npm install --silent
