FROM cypress/included:3.8.0

ENV APP_HOME /usr/src/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY . ./
RUN rm package-lock.json

VOLUME ["/tmp/app/allure-report"]

# install packages
RUN apt-get update && \
    apt-get install -y curl \
    wget \
    openjdk-8-jdk
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

EXPOSE 9001

# Override default entrypoint from cypress/included
ENTRYPOINT []

RUN npm install -g wait-on --silent
RUN npm install --silent
COPY /usr/src/app/allure-report /tmp/app/allure-report