export {
  computeBlockType,
  getContent,
  getContentInfo,
  getDecoratedValue,
  getSelection,
  getSelectionInfo,
  getSelectedLength,
  moveSelectionToEnd,
  resetBlockType,
  isASCIIChar,
  replaceText,
  hasBlockStyle,
  hasInlineStyle,
  blockStyleFn,
} from "./utils";
