export default {
  black: {
    background: "var(--nav-primary-bg-default)",
    color: "var(--nav-primary-label-default)",
    backgroundHover: "var(--nav-primary-bg-hover)",
    colorHover: "var(--nav-primary-label-hover)",
    backgroundActive: "var(--nav-primary-bg-active)",
    colorActive: "var(--nav-primary-label-active)",
    submenuOpenedBackground: "var(--nav-primary-bg-child)",
    submenuItemBackground: "var(--nav-primary-bg-child)",
    title: "var(--container-standard-inverse-txt-alt)",
    alternate: "var(--nav-primary-bg-child-alt)",
    divider: "var(--nav-primary-divider)",
    fullScreenHeader: "var(--nav-primary-bg-child)",
  },
  white: {
    background: "var(--nav-tertiary-bg-default)",
    color: "var(--nav-tertiary-label-default)",
    backgroundHover: "var(--nav-tertiary-bg-hover)",
    colorHover: "var(--nav-tertiary-label-hover)",
    backgroundActive: "var(--nav-tertiary-bg-active)",
    colorActive: "var(--nav-tertiary-label-active)",
    submenuOpenedBackground: "var(--nav-tertiary-bg-child)",
    submenuItemBackground: "var(--nav-tertiary-bg-child)",
    title: "var(--container-standard-txt-alt)",
    alternate: "var(--nav-tertiary-bg-child-alt)",
    divider: "var(--nav-tertiary-divider)",
    fullScreenHeader: "var(--nav-tertiary-bg-child-alt)",
  },
};
