/**
 *
 * Util that maps old theme properties to design tokens
 * or assigns hardcoded values if equivalent does not
 * exist in old theme.
 *
 * Its purpose is to provide new property values to
 * old themes so both of them can be compatible.
 *
 * I see no other way, than hardcode those keys and
 * assign them values. Hopefully this job will be
 * done only once in the beginning.
 *
 */
export default (theme) => ({
  ...theme,
  metaName: "Base Theme",
  metaPublic: "true",
  colorsLogo: "#00D639",
  colorsYin030: "rgba(0,0,0,0.3)",
  colorsYin055: "rgba(0,0,0,0.55)",
  colorsYin065: "rgba(0,0,0,0.65)",
  colorsYin090: "rgba(0,0,0,0.9)",
  colorsComponentsNavigation500: "#008146",
  colorsComponentsNavigation600: "#006738",
  colorsComponentsNavigation700: "#004D2A",
  colorsComponentsNavigation1000: "#000000",
  colorsComponentsNavigation000: "#FFFFFF",
  colorsComponentsNavigationTransparent: "rgba(0,0,0,0)",
  colorsUtilityMajor100: "#CCD6DB",
  colorsUtilityMajor150: "#B3C2C9",
  colorsUtilityMajor200: "#99ADB7",
  colorsUtilityMajor300: "#668494",
  colorsUtilityMajor400: "#335B70",
  colorsUtilityMajor500: "#00324C",
  colorsUtilityMajor800: "#00141E",
  colorsUtilityMajor1000: "#000000",
  colorsUtilityMajor000: "#FFFFFF",
  colorsUtilityMajor025: "#F2F5F6",
  colorsUtilityMajor050: "#E6EBED",
  colorsUtilityMajor075: "#D9E0E4",
  colorsUtilityMajorTransparent: "rgba(0,0,0,0)",
  colorsUtilityDisabled400: "#F2F5F6",
  colorsUtilityDisabled500: "#E6EBED",
  colorsUtilityDisabled600: "#CCD6DB",
  colorsUtilityReadOnly400: "#F2F5F6",
  colorsUtilityReadOnly500: "#E6EBED",
  colorsUtilityReadOnly600: "#CCD6DB",
  colorsActionMajor150: "#B3D9C8",
  colorsActionMajor500: theme.colors.primary,
  colorsActionMajor600: theme.colors.secondary,
  colorsActionMajor700: "#004D2A",
  colorsActionMajor1000: "#000000",
  colorsActionMajor000: "#FFFFFF",
  colorsActionMajorTransparent: "rgba(0,0,0,0)",
  colorsActionMinor100: "#E6EBED",
  colorsActionMinor200: "#CCD6DB",
  colorsActionMinor300: "#99ADB7",
  colorsActionMinor400: "#668494",
  colorsActionMinor500: "#335B70",
  colorsActionMinor600: "#00324C",
  colorsActionMinor1000: "#000000",
  colorsActionMinor000: "#FFFFFF",
  colorsActionMinor025: "#FAFBFB",
  colorsActionMinor050: "#F2F5F6",
  colorsActionMinorTransparent: "rgba(0,0,0,0)",
  colorsActionDisabled400: "#F2F5F6",
  colorsActionDisabled500: theme.colors.disabled.disabled,
  colorsActionDisabled600: "#CCD6DB",
  colorsActionReadOnly400: "#F2F5F6",
  colorsActionReadOnly500: "#E6EBED",
  colorsActionReadOnly600: "#CCD6DB",
  colorsSemanticNeutral200: "#CCD6DB",
  colorsSemanticNeutral500: "#335B70",
  colorsSemanticNeutral600: "#00324C",
  colorsSemanticNeutral1000: "#000000",
  colorsSemanticNeutral000: "#FFFFFF",
  colorsSemanticNeutralTransparent: "rgba(0,0,0,0)",
  colorsSemanticFocus250: "#FFDA80",
  colorsSemanticFocus500: theme.colors.focus,
  colorsSemanticFocus1000: "#000000",
  colorsSemanticFocus000: "#FFFFFF",
  colorsSemanticFocusTransparent: "rgba(0,0,0,0)",
  colorsSemanticPositive500: theme.colors.success,
  colorsSemanticPositive600: "#006e1a",
  colorsSemanticPositive1000: "#000000",
  colorsSemanticPositive000: "#FFFFFF",
  colorsSemanticPositiveTransparent: "rgba(0,0,0,0)",
  colorsSemanticNegative500: theme.colors.error,
  colorsSemanticNegative600: theme.colors.destructive.hover,
  colorsSemanticNegative1000: "#000000",
  colorsSemanticNegative000: "#FFFFFF",
  colorsSemanticNegativeTransparent: "rgba(0,0,0,0)",
  colorsSemanticCaution400: "#f28533",
  colorsSemanticCaution500: theme.colors.warning,
  colorsSemanticCaution600: "#bf5200",
  colorsSemanticCaution1000: "#000000",
  colorsSemanticCaution000: "#FFFFFF",
  colorsSemanticCautionTransparent: "rgba(0,0,0,0)",
  colorsSemanticInfo150: "#b3cfe5",
  colorsSemanticInfo500: theme.colors.info,
  colorsSemanticInfo600: "#004d86",
  colorsSemanticInfo1000: "#000000",
  colorsSemanticInfo000: "#FFFFFF",
  colorsSemanticInfoTransparent: "rgba(0,0,0,0)",
  sizing10: "1px",
  sizing100: "8px",
  sizing125: "10px",
  sizing150: "12px",
  sizing175: "14px",
  sizing200: "16px",
  sizing250: "20px",
  sizing300: "24px",
  sizing350: "28px",
  sizing375: "30px",
  sizing400: "32px",
  sizing500: "40px",
  sizing600: "48px",
  sizing700: "56px",
  sizing800: "64px",
  sizing900: "72px",
  sizing1000: "80px",
  sizing025: "2px",
  sizing050: "4px",
  sizing075: "6px",
  sizingLogowidth: "40px",
  spacing000: `${theme.space[0]}px`, // 0px
  spacing025: "2px",
  spacing050: "4px",
  spacing075: "6px",
  spacing100: `${theme.space[1]}px`, // 8px
  spacing125: "10px",
  spacing150: "12px",
  spacing200: `${theme.space[2]}px`, // 16px
  spacing250: "20px",
  spacing300: `${theme.space[3]}px`, // 24px
  spacing400: `${theme.space[4]}px`, // 32px
  spacing500: `${theme.space[5]}px`, // 40px
  spacing600: `${theme.space[6]}px`, // 48px
  spacing700: `${theme.space[7]}px`, // 56px
  spacing800: `${theme.space[8]}px`, // 64px
  spacing900: `${theme.space[9]}px`, // 72px
  borderWidth100: "1px",
  borderWidth200: "2px",
  borderWidth300: "3px",
  borderWidth400: "4px",
  borderWidth000: "0px",
  fontSizes100: theme.text.size,
  fontSizes200: "16px",
  fontSizes300: "18px",
  fontSizes400: "20px",
  fontSizes500: "22px",
  fontSizes600: "24px",
  fontSizes700: "32px",
  fontSizes800: "48px",
  fontSizes900: "56px",
  fontSizes1000: "64px",
  fontSizes010: "10px",
  fontSizes025: "12px",
  fontSizes050: "13px",
  boxShadow100: {
    x: "0",
    y: "10px",
    blur: "10px",
    spread: "0",
    color: "rgba(0,20,29,0.1)",
  },
  boxShadow200: {
    x: "0",
    y: "20px",
    blur: "40px",
    spread: "0",
    color: "rgba(0,20,29,0.1)",
  },
  boxShadow300: {
    x: "0",
    y: "30px",
    blur: "60px",
    spread: "0",
    color: "rgba(0,20,29,0.1)",
  },
  boxShadow400: {
    x: "0",
    y: "50px",
    blur: "80px",
    spread: "0",
    color: "rgba(0,20,29,0.1)",
  },
  opacity100: "10%",
  opacity200: "20%",
  opacity300: "30%",
  opacity400: "40%",
  opacity500: "50%",
  opacity550: "55%",
  opacity600: "60%",
  opacity650: "65%",
  opacity700: "70%",
  opacity800: "80%",
  opacity900: "90%",
  fontWeights400: "Regular Beta",
  fontWeights500: "Medium Beta",
  fontWeights600: "SemiBold Beta",
  fontWeights700: "Bold Beta",
  lineHeights400: "125%",
  lineHeights500: "150%",
  fontFamiliesDefault: "Sage UI",
  fontFamiliesIos: "San Francisco",
  fontFamiliesAndroid: "Roboto",
  fontFamiliesOther: "Open Sans",
  borderRadiusCircle: "50%",
  typographyButtonLabelS: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyButtonLabelM: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyButtonLabelL: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleXs: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleS: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleMs: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleM: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleMl: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleL: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyDialogTitleXl: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "125%",
    fontSize: "20px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFlashTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFlashTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldLabelXs: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldLabelS: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldLabelM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldLabelL: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldHintTextXs: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldHintTextS: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldHintTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldHintTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldErrorMessageXs: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldErrorMessageS: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldErrorMessageM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldErrorMessageL: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCautionMessageXs: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCautionMessageS: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCautionMessageM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCautionMessageL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldInputTextXs: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldInputTextS: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldInputTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldInputTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldDropdownOptionsXs: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldDropdownOptionsS: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldDropdownOptionsM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldDropdownOptionsL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldSecondLabelXs: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldSecondLabelS: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldSecondLabelM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldSecondLabelL: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCharacterCountXs: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCharacterCountS: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCharacterCountM: {
    fontFamily: "Sage UI",
    lineHeight: "150%",
    fontWeight: "Regular Beta",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyFormFieldCharacterCountL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyLinkTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyLinkTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyMessageHeadingM: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyMessageHeadingL: {
    fontFamily: "Sage UI",
    fontWeight: "Bold Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyMessageTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyMessageTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyPillLabelS: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "10px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyPillLabelM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "12px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyPillLabelL: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyPillLabelXl: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographySwitchOptionLabelM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "12px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographySwitchOptionLabelL: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyTableHeaderTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Medium Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyTableCellTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyTooltipTextM: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "14px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
  typographyTooltipTextL: {
    fontFamily: "Sage UI",
    fontWeight: "Regular Beta",
    lineHeight: "150%",
    fontSize: "16px",
    letterSpacing: "0%",
    paragraphSpacing: "0px",
  },
});
