export default {
  APP_VALUE_UPDATED: "APP_VALUE_UPDATED",
  APP_DELETE_ROW: "APP_DELETE_ROW",
  APP_TABLE_UPDATED: "APP_TABLE_UPDATED",
  APP_TABLE_MANUALLY_UPDATED: "APP_TABLE_MANUALLY_UPDATED",
  APP_EDIT_CONTENT: "APP_EDIT_CONTENT",
  APP_SAVE_EDITED_CONTENT: "APP_SAVE_EDITED_CONTENT"
}
