export default {
  APP_VALUE_UPDATED: "APP_VALUE_UPDATED",
  APP_DELETE_ROW: "APP_DELETE_ROW",
  APP_TABLE_UPDATED: "APP_TABLE_UPDATED",
  APP_TABLE_MANUALLY_UPDATED: "APP_TABLE_MANUALLY_UPDATED",
  APP_TABLE_ROW_SELECTED: "APP_TABLE_ROW_SELECTED",
  APP_ALL_TABLE_ROWS_SELECTED: "APP_ALL_TABLE_ROWS_SELECTED"
}
