name: 🏗️ New feature request
description: Is there something that we should implement? Let us know!
labels:
  - Enhancement
  - triage

body:
  - type: markdown
    attributes:
      value: |
        > ⚠️ **WARNING: This bug report is public**
        > Please do not include any confidential or commercially sensitive information.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of the new feature. Please make the reason and use cases as detailed as possible. If applicable, add screenshots or screen recordings to help explain the request.

        If you intend to submit a PR for this issue, tell us in description. Thanks!
      placeholder: As a developer using Carbon, I want to [goal] so that [benefit].
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Demo URL
      description: >-
        If possible, please provide a link via [our Stackblitz template](https://stackblitz.com/fork/github/Parsium/carbon-starter) that can demonstrate the feature you are requesting.
      placeholder: Reproduction URL
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        A clear and concise description of any alternative solutions or features you've tried or considered.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Anything else we should know?
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Confidentiality
      description: >-
        By submitting this issue, you confirm that there is no confidential or commercially sensitive information included.
      options:
        - label: I confirm there is no confidential or commercially sensitive information included.
          required: true
