name: Feature Request
description: Is there something that we should implement? Let us know!
labels:
  - Enhancement
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ This feature request is public
        Please do not include any confidential or commercially sensitive information.

        ---
  - type: textarea
    id: desired-behaviour
    attributes:
      label: Desired behaviour
      description: |
        Please give a clear and concise description of the desired behaviour.
        If applicable, add screenshots or screen recording of a CodeSandbox to help explain the request. You can paste these directly into GitHub.
        We provide Codesandbox templates with Carbon and dependencies pre-loaded, using either [Typescript](https://codesandbox.io/p/sandbox/carbon-quickstart-typescript-6sjfuz) or [Javascript](https://codesandbox.io/p/sandbox/carbon-quickstart-j5pb2).
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current behaviour
      description: |
        Please give a clear and concise description of the current behaviour.
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
    validations:
      required: false
  - type: input
    id: url
    attributes:
      label: CodeSandbox or Storybook URL
      description: >-
        Please fork one of our templates ([Typescript](https://codesandbox.io/p/sandbox/carbon-quickstart-typescript-6sjfuz) or [Javascript](https://codesandbox.io/s/carbon-quickstart-j5pb2)), and ensure you save your changes.
        Alternatively, if your issue relates to [Storybook](https://carbon.sage.com) please link to the story.
      placeholder: https://codesandbox.io/s/carbon-quickstart-j5pb2
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Anything else we should know?
      placeholder: Please describe any alternatives you've considered
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Confidentiality
      description: >-
        By submitting this issue, you confirm that there is no confidential or commercially sensitive information included.
      options:
        - label: I confirm there is no confidential or commercially sensitive information included.
          required: true
