// Auto-generated by scripts/generate_tokens/generate_tokens.mjs — do not edit

export const containerSizeDialogMaxwidthS = "540px";
export const containerSizeDialogMaxwidthM = "850px";
export const containerSizeDialogMaxwidthL = "1080px";
