export default [
  { name: 'Grey', children: [
    { name: '$grey-dark-plus', hex: '#1B1D21', fontContrast: 'light' },
    { name: '$dark-blue-plus', hex: '#262A33', fontContrast: 'light' },
    { name: '$grey-dark-blue', hex: '#3C424F', fontContrast: 'light' },
    { name: '$grey-dark-blue-90', hex: '#4F5460', fontContrast: 'light' },
    { name: '$grey-dark-blue-80', hex: '#636872', fontContrast: 'light' },
    { name: '$grey-dark-blue-70', hex: '#767A83', fontContrast: 'dark' },
    { name: '$grey-dark-blue-60', hex: '#8A8E95', fontContrast: 'dark' },
    { name: '$grey-dark-blue-50', hex: '#9DA0A7', fontContrast: 'dark' },
    { name: '$grey-dark-blue-40', hex: '#B1B3B9', fontContrast: 'dark' },
    { name: '$grey-dark-blue-30', hex: '#C4C6CA', fontContrast: 'dark' },
    { name: '$grey-dark-blue-25', hex: '#CED0D3', fontContrast: 'dark' },
    { name: '$grey-dark-blue-20', hex: '#D8D9DC', fontContrast: 'dark' },
    { name: '$grey-dark-blue-15', hex: '#E2E3E5', fontContrast: 'dark' },
    { name: '$grey-dark-blue-10', hex: '#EBECED', fontContrast: 'dark' },
    { name: '$grey-dark-blue-5', hex: '#F5F6F7', fontContrast: 'dark' },
  ] },
  { name: 'Green', children: [
    { name: '$green-bright', hex: '#00DC00', fontContrast: 'dark' },
    { name: '$green-apple', hex: '#50B848', fontContrast: 'dark' },
    { name: '$green-apple-05', hex: '#F6FBF6', fontContrast: 'dark' },
    { name: '$green-apple-20', hex: '#DCF1DA', fontContrast: 'dark' },
    { name: '$green-bright-dull', hex: '#38C72A', fontContrast: 'dark' },
  ] },
  { name: 'Orange', children: [
    { name: '$orange-bright', hex: '#FF7D00', fontContrast: 'dark' },
    { name: '$orange-bright-05', hex: '#FFF8F2', fontContrast: 'dark' },
    { name: '$orange-bright-20', hex: '#FFE4CC', fontContrast: 'dark' },
  ] },
  { name: 'Blue', children: [
    { name: '$blue', hex: '#255BC7', fontContrast: 'light' },
    { name: '$blue-bright', hex: '#1963F6', fontContrast: 'light' },
    { name: '$blue-sky', hex: '#1573E6', fontContrast: 'dark' },
    { name: '$blue-sky-05', hex: '#F3F8FE', fontContrast: 'dark' },
    { name: '$blue-sky-10', hex: '#E7F1FC', fontContrast: 'dark' },
    { name: '$blue-sky-20', hex: '#D0E3FA', fontContrast: 'dark' },
    { name: '$blue-light', hex: '#4782F7', fontContrast: 'dark' },
    { name: '$azul', hex: '#004089', fontContrast: 'light' },
  ] },
  { name: 'Red', children: [
    { name: '$red', hex: '#D63F40', fontContrast: 'dark' },
    { name: '$red-light', hex: '#E42C2D', fontContrast: 'dark' },
    { name: '$red-dark', hex: '#C11E20', fontContrast: 'light' },
    { name: '$red-05', hex: '#FDF5F5', fontContrast: 'dark' },
    { name: '$red-20', hex: '#F7D9D9', fontContrast: 'dark' },
  ] },
  { name: 'Yellow', children: [
    { name: '$yellow', hex: '#FFAB00', fontContrast: 'dark' },
    { name: '$yellow-05', hex: '#FFFBF2', fontContrast: 'dark' },
    { name: '$yellow-20', hex: '#FFEECC', fontContrast: 'dark' },
  ] },
  { name: 'Magenta', children: [
    { name: '$magenta', hex: '#ED1C5F', fontContrast: 'dark' },
    { name: '$magenta-dull', hex: '#CA2A60', fontContrast: 'light' },
    { name: '$magenta-light', hex: '#F32E6D', fontContrast: 'dark' },
  ] },
  { name: 'Purple', children: [
    { name: '$purple', hex: '#663399', fontContrast: 'light' },
    { name: '$purple-05', hex: '#F7F5FA', fontContrast: 'dark' },
    { name: '$purple-20', hex: '#E0D6EB', fontContrast: 'dark' },
] } ];
