const dlsConfig = {
  backgroundSize: {
    "extra-small": "16px",
    small: "24px",
    medium: "32px",
    large: "40px",
    "extra-large": "56px",
  },
  backgroundShape: {
    square: "0%",
    "rounded-rect": "20%",
    circle: "50%",
  },
  iconSize: {
    small: "16px",
    medium: "24px",
    large: "32px",
    "extra-large": "48px",
  },
};

export const ICON_TOOLTIP_POSITIONS = ["bottom", "left", "right", "top"];
export const ICON_SHAPES = ["circle", "rounded-rect", "square"];
export const ICON_SIZES = [
  "extra-small",
  "small",
  "medium",
  "large",
  "extra-large",
];
export const ICON_FONT_SIZES = ["small", "medium", "large", "extra-large"];
export const ICONS = [
  "add",
  "alert",
  "analysis",
  "arrow_down",
  "arrow_left",
  "arrow_left_boxed",
  "arrow_left_right_small",
  "arrow_left_small",
  "arrow_right",
  "arrow_right_small",
  "arrow_up",
  "attach",
  "bank",
  "basket",
  "basket_with_squares",
  "bin",
  "blocked",
  "blocked_square",
  "block_arrow_right",
  "bold",
  "boxed_shapes",
  "bulk_destroy",
  "bullet_list",
  "bullet_list_dotted",
  "bullet_list_numbers",
  "business",
  "calendar",
  "calendar_today",
  "call",
  "camera",
  "card_view",
  "caret_down",
  "caret_left",
  "caret_right",
  "caret_up",
  "caret_large_down",
  "caret_large_left",
  "caret_large_right",
  "caret_large_up",
  "cart",
  "chat",
  "chart_bar",
  "chart_line",
  "chart_pie",
  "chat_notes",
  "chevron_down",
  "chevron_left",
  "chevron_right",
  "chevron_up",
  "chevron_down_thick",
  "chevron_left_thick",
  "chevron_right_thick",
  "chevron_up_thick",
  "circle_with_dots",
  "circles_connection",
  "clock",
  "close",
  "coins",
  "collaborate",
  "computer_clock",
  "connect",
  "copy",
  "credit_card",
  "credit_card_slash",
  "cross",
  "cross_circle",
  "csv",
  "delete",
  "delivery",
  "disputed",
  "document_right_align",
  "document_tick",
  "document_vertical_lines",
  "download",
  "drag",
  "drag_vertical",
  "draft",
  "dropdown",
  "duplicate",
  "edit",
  "edited",
  "email",
  "email_switch",
  "ellipsis_horizontal",
  "ellipsis_vertical",
  "envelope_dollar",
  "envelope_euro",
  "error",
  "error_square",
  "euro",
  "expand",
  "factory",
  "favourite",
  "favourite_lined",
  "fax",
  "feedback",
  "file_excel",
  "file_generic",
  "file_image",
  "file_pdf",
  "file_word",
  "files_leaning",
  "filter",
  "filter_new",
  "fit_height",
  "fit_width",
  "flag",
  "folder",
  "gift",
  "graph",
  "grid",
  "help",
  "hide",
  "home",
  "image",
  "in_progress",
  "in_transit",
  "individual",
  "info",
  "italic",
  "key",
  "ledger",
  "ledger_arrow_left",
  "ledger_arrow_right",
  "link",
  "list_view",
  "locked",
  "location",
  "logout",
  "lookup",
  "marker",
  "message",
  "messages",
  "minus",
  "minus_large",
  "mobile",
  "money_bag",
  "pause",
  "pause_circle",
  "pdf",
  "people",
  "people_switch",
  "person",
  "person_info",
  "person_tick",
  "phone",
  "play",
  "play_circle",
  "plus",
  "plus_large",
  "pound",
  "print",
  "progress",
  "progressed",
  "question",
  "refresh",
  "refresh_clock",
  "remove",
  "sage_coin",
  "save",
  "scan",
  "search",
  "services",
  "settings",
  "share",
  "shop",
  "sort_down",
  "sort_up",
  "spanner",
  "split",
  "split_container",
  "square_dot",
  "squares_nine",
  "stacked_boxes",
  "stacked_squares",
  "submitted",
  "sync",
  "tag",
  "three_boxes",
  "tick",
  "tick_circle",
  "undo",
  "unlocked",
  "upload",
  "uploaded",
  "video",
  "view",
  "warning",
  "admin",
  "arrow",
  "contacts",
  "create",
  "disconnect",
  "entry",
  "go",
  "lightbulb_off",
  "lightbulb_on",
  "none",
  "old_warning",
  "piggy_bank",
  "question_hollow",
  "question_mark",
  "settings_old",
  "talk",
  "true_tick",
];

export default dlsConfig;
