export default [
  { name: 'Communication', children: [
    { name: 'phone', type: 'phone' },
    { name: 'mobile', type: 'mobile' },
    { name: 'message', type: 'message' },
    { name: 'marker', type: 'marker' }
  ] },
  { name: 'Business', children: [
    { name: 'person', type: 'person' },
    { name: 'people', type: 'people' },
    { name: 'business', type: 'business' },
    { name: 'shop', type: 'shop' }
  ] },
  { name: 'Primary Navigation', children: [
    { name: 'home', type: 'home' },
    { name: 'settings', type: 'settings' },
    { name: 'search', type: 'search' },
    { name: 'feedback', type: 'feedback' },
    { name: 'logout', type: 'logout' },
    { name: 'alert', type: 'alert' },
    { name: 'talk', type: 'talk' }
  ] },
  { name: 'Actions', children: [
    { name: 'calendar', type: 'calendar' },
    { name: 'dropdown', type: 'dropdown' },
    { name: 'add', type: 'add' },
    { name: 'minus', type: 'minus' },
    { name: 'edit', type: 'edit' },
    { name: 'edited', type: 'edited' },
    { name: 'ellipsis', type: 'ellipsis' },
    { name: 'favourite', type: 'favourite' },
    { name: 'favourite_lined', type: 'favourite_lined' },
    { name: 'credit_card', type: 'credit_card' },
    { name: 'save', type: 'save' },
    { name: 'uploaded', type: 'uploaded' },
    { name: 'question', type: 'question' },
    { name: 'question_hollow', type: 'question_hollow' },
    { name: 'info', type: 'info' },
    { name: 'download', type: 'download' },
    { name: 'upload', type: 'upload' },
    { name: 'share', type: 'share' },
    { name: 'close', type: 'close' },
    { name: 'cross', type: 'cross' },
    { name: 'filter', type: 'filter' },
    { name: 'refresh', type: 'refresh' },
    { name: 'sync', type: 'sync' },
    { name: 'attach', type: 'attach' },
    { name: 'camera', type: 'camera' },
    { name: 'image', type: 'image' },
    { name: 'folder', type: 'folder' },
    { name: 'chat', type: 'chat' },
    { name: 'help', type: 'help' },
    { name: 'connect', type: 'connect' },
    { name: 'disconnect', type: 'disconnect' },
    { name: 'split', type: 'split' },
    { name: 'filter_new', type: 'filter_new' },
    { name: 'delivery', type: 'delivery' },
    { name: 'chat_notes', type: 'chat_notes' },
    { name: 'view', type: 'view' },
    { name: 'bullet_list', type: 'bullet_list' },
    { name: 'lightbulb_off', type: 'lightbulb_off' },
    { name: 'lightbulb_on', type: 'lightbulb_on' }
  ] },
  { name: 'Batch Actions', children: [
    { name: 'cart', type: 'cart' },
    { name: 'delete', type: 'delete' },
    { name: 'print', type: 'print' },
    { name: 'csv', type: 'csv' },
    { name: 'pdf', type: 'pdf' },
    { name: 'duplicate', type: 'duplicate' },
    { name: 'copy', type: 'copy' },
    { name: 'fax', type: 'fax' }
  ] },
  { name: 'Navigation', children: [
    { name: 'chevron_up', type: 'chevron_up' },
    { name: 'chevron_down', type: 'chevron_down' },
    { name: 'chevron_right', type: 'chevron_right' },
    { name: 'chevron_left', type: 'chevron_left' },
    { name: 'link', type: 'link' },
    { name: 'list_view', type: 'list_view' },
    { name: 'card_view', type: 'card_view' },
    { name: 'sort_down', type: 'sort_down' },
    { name: 'sort_up', type: 'sort_up' },
    { name: 'arrow_left', type: 'arrow_left' },
    { name: 'arrow_right', type: 'arrow_right' },
    { name: 'arrow_down', type: 'arrow_down' },
    { name: 'arrow_up', type: 'arrow_up' },
    { name: 'drag_vertical', type: 'drag_vertical' },
    { name: 'drag', type: 'drag' },
    { name: 'fit_height', type: 'fit_height' },
    { name: 'fit_width', type: 'fit_width' }
  ] },
  { name: 'System Status', children: [
    { name: 'error', type: 'error' },
    { name: 'warning', type: 'warning' },
    { name: 'tick', type: 'tick' },
    { name: 'draft', type: 'draft' },
    { name: 'progressed', type: 'progressed' },
    { name: 'in_progress', type: 'in_progress' },
    { name: 'locked', type: 'locked' },
    { name: 'unlocked', type: 'unlocked' },
    { name: 'gift', type: 'gift' },
    { name: 'clock', type: 'clock' },
    { name: 'blocked', type: 'blocked' },
    { name: 'key', type: 'key' },
    { name: 'chart_line', type: 'chart_line' },
    { name: 'chart_pie', type: 'chart_pie' },
    { name: 'chart_bar', type: 'chart_bar' },
    { name: 'blocked_square', type: 'blocked_square' },
    { name: 'disputed', type: 'disputed' }
  ] } ];
