export default {
  // 'alert':                require('components/alert/definition').default,
  // 'animated-menu-button': require('components/animated-menu-button/definition').default,
  // 'app-wrapper':          require('components/app-wrapper/definition').default,
  // 'button':               require('components/button/definition').default,
  // 'button-toggle':        require('components/button-toggle/definition').default,
  // 'carousel':             require('components/carousel/definition').default,
  // 'checkbox':             require('components/checkbox/definition').default,
  // 'confirm':              require('components/confirm/definition').default,
  // 'content':              require('components/content/definition').default,
  // 'create':               require('components/create/definition').default,
  // 'date':                 require('components/date/definition').default,
  // 'date-range':           require('components/date-range/definition').default,
  // 'decimal':              require('components/decimal/definition').default,
  // 'detail':               require('components/detail/definition').default,
  // 'dialog':               require('components/dialog/definition').default,
  // 'dialog-full-screen':   require('components/dialog-full-screen/definition').default,
  // 'dropdown':             require('components/dropdown/definition').default,
  // 'dropdown-filter':      require('components/dropdown-filter/definition').default,
  //'dropdown-filter-ajax': require('components/dropdown-filter-ajax/definition').default,
  // 'fieldset':             require('components/fieldset/definition').default,
  // 'filter':               require('components/filter/definition').default,
  // 'flash':                require('components/flash/definition').default,
  //'form':                 require('components/form/definition').default,
  // 'heading':              require('components/heading/definition').default,
  // 'help':                 require('components/help/definition').default,
  // 'i18n':                 require('components/i18n/definition').default,
  // 'icon':                 require('components/icon/definition').default,
  // 'link':                 require('components/link/definition').default,
  // 'menu':                 require('components/menu/definition').default,
  // 'message':              require('components/message/definition').default,
  // 'multi-action-button':  require('components/multi-action-button/definition').default,
  // 'navigation-bar':       require('components/navigation-bar/definition').default,
  // 'number':               require('components/number/definition').default,
  // 'pill':                 require('components/pill/definition').default,
  // 'pod':                  require('components/pod/definition').default,
  // 'portrait':             require('components/portrait/definition').default,
  // 'profile':              require('components/profile/definition').default,
  // 'radio-button':         require('components/radio-button/definition').default,
  // 'row':                  require('components/row/definition').default,
  // 'show-edit-pod':        require('components/show-edit-pod/definition').default,
  // 'sidebar':              require('components/sidebar/definition').default,
  // 'spinner':              require('components/spinner/definition').default,
  // 'split-button':         require('components/split-button/definition').default,
  //'table':                require('components/table/definition').default,
  //'table-ajax':           require('components/table-ajax/definition').default,
  'tabs':                 require('components/tabs/definition').default,
  'textarea':             require('components/textarea/definition').default,
  'textbox':              require('components/textbox/definition').default,
  // 'toast':                require('components/toast/definition').default,
  // 'tooltip':              require('components/tooltip/definition').default
};
