const dummyMentionsData = [
  "Aayla Secura",
  "Admiral Dodd Rancit",
  "Aurra Sing",
  "BB-8",
  "Bo-Katan Kryze",
  "Breha Antilles-Organa",
  "C-3PO",
  "Captain Quarsh Panaka",
  "Chewbacca",
  "Darth Tyranus",
  "Daultay Dofine",
  "Dexter Jettster",
  "Ebe E. Endocott",
  "Eli Vanto",
  "Ezra Bridger",
  "Faro Argyus",
  "Finis Valorum",
  "FN-2003",
  'Garazeb "Zeb" Orrelios',
  "Grand Inquisitor",
  "Greeata Jendowanian",
  "Hammerhead",
  "Han Solo",
  "Hevy",
  "Hondo Ohnaka",
  "Ima-Gun Di",
  "Inquisitors",
  "Inspector Thanoth",
  "Jabba",
  "Janus Greejatus",
  "Jaxxon",
  "K-2SO",
  "Kanan Jarrus",
  "Kylo Ren",
  "L3-37",
  "Lieutenant Kaydel Ko Connix",
  "Luke Skywalker",
  "Mace Windu",
  "Maximilian Veers",
  "Mother Talzin",
  "Nahdar Vebb",
  "Nahdonnis Praji",
  "Nien Nunb",
  "Obi-Wan Kenobi",
  "Odd Ball",
  "Orrimarko",
  "Petty Officer Thanisson",
  "Pooja Naberrie",
  "PZ-4CO",
  "Quarrie",
  "Quiggold",
  "Quinlan Vos",
  "R2-D2",
  "Raymus Antilles",
  "Ree-Yees",
  "Sana Starros",
  "Shmi Skywalker",
  "Shu Mai",
  "Tallissan Lintra",
  "Tarfful",
  "Thane Kyrell",
  "U9-C4",
  "Unkar Plutt",
  "Val Beckett",
  "Vice Admiral Amilyn Holdo",
  "Vober Dand",
  "WAC-47",
  "Wedge Antilles",
  "Wicket W. Warrick",
  "Xamuel Lennox",
  "Yaddle",
  "Yarael Poof",
  "Yoda",
  "Zam Wesell",
  "Ziro the Hutt",
  "Zuckuss",
];

export default dummyMentionsData;
