export { default as TableHead } from "./table-head";
export { default as TableBody } from "./table-body";
export type { TableBodyProps } from "./table-body";
export { default as TableRow } from "./table-row";
export type { TableRowProps } from "./table-row";
export { default as TableCell } from "./table-cell";
export type { TableCellProps } from "./table-cell";
export { default as Table } from "./table.component";
export type { TableProps } from "./table.component";
export { default as TableFoot } from "./table-foot";
export { default as TableHeader } from "./table-header";
export type { TableHeaderCellProps } from "./table-header";
