name: Cypress-Windows

on: [pull_request]
  # schedule:
  # every day at 03:00
  # - cron:  '0 3 * * *'

jobs:
  windows-parallel:
    if: ${{ github.event.pull_request.head.repo.full_name == 'Sage/carbon' }}
    name: Windows-${{ matrix.browser }}
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        browser: ["chrome", "edge"]
        # run 20 copies of the current job in parallel
        # and they will load balance all specs
        containers:
          [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: "http://localhost:9001"
          wait-on-timeout: 250
          record: true
          parallel: true
          browser: ${{ matrix.browser }}
          group: Windows-${{ matrix.browser }}
          spec: "./cypress/features/regression/**/*.feature"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: "true"
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
