name: Cypress-MacOS-chrome

on: [pull_request]
  # schedule:
    # every day at 01:00
    # - cron:  '0 1 * * *'

jobs:
  mac-os-chrome-parallel:
    if: ${{ github.event.pull_request.head.repo.full_name == 'Sage/carbon' }} 
    name: MacOS-chrome
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 5 copies of the current job in parallel
        # and they will load balance all specs
        containers: [ 1, 2, 3, 4, 5 ]
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:9001'
          wait-on-timeout: 250
          record: true
          parallel: true
          browser: chrome
          group: MacOS-chrome
          spec: './cypress/features/regression/**/*.feature'
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: 'true'
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}