name: PR tasks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  trigger-chromatic:
    # do not run if a fork or a draft
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - id: dispatch_chromatic
        name: Dispatch Chromatic workflow
        run: |
          gh workflow run chromatic.yml --ref master -f number=${{ github.event.pull_request.number }} --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.CHROMATIC_WORKFLOW_TOKEN }}
